In [1]:
# wap to find common element in a list.
l=[1,2,3,4,5]
l2=[5,6,7,8,9]
f=0
for i in l:
    for j in l2:
        if i==j:
            f=0
            print("Commomn Element is present.")
            break
if f==1:
    pass 
else:
    print("-1")

Commomn Element is present.
-1


In [13]:
a = [1,2,3,4]
b = [4,5,6,2]
def common(a,b):
    for i in a:
        for j in b:
            if i == j:
                print( i)
            else:
                print('-1')
                

In [14]:
common(a,b)

-1
-1
-1
-1
-1
-1
-1
2
-1
-1
-1
-1
4
-1
-1
-1


In [15]:
# numpy
#wap to make a array of 2 by 3.

import numpy as np

In [19]:
x = np.array([[1,3],[67,89],[1,2]])

In [20]:
x

array([[ 1,  3],
       [67, 89],
       [ 1,  2]])

In [21]:
x.shape

(3, 2)

In [22]:
x.size

6

In [23]:
x = np.array([1,2,'python'])

In [24]:
x

array(['1', '2', 'python'], dtype='<U11')

In [25]:
type(x)

numpy.ndarray

In [26]:
x.shape

(3,)

In [27]:
x.size

3

In [31]:
#ones & zeros
np.zeros(0)

array([], dtype=float64)

In [32]:
np.zeros(1)

array([0.])

In [37]:
np.zeros([10,20])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

In [64]:
# WAp to make a 3d matrix of 0 .
z = np.zeros([5,3,3])

In [65]:
z.shape

(5, 3, 3)

In [66]:
z.size

45

In [67]:
z.ndim

3

In [68]:
z

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [70]:
y = np.ones(0)

In [71]:
y

array([], dtype=float64)

In [75]:
y = np.ones([5,2])

In [76]:
y

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [78]:
#wap to make a data of ones of having the shape
# of 5 by 6 with the help of tuple.

np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [89]:
# arange
np.arange(100,2,-1)

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,
        48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,
        35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,
        22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10,
         9,   8,   7,   6,   5,   4,   3])

In [99]:
# empty function
np.empty(51)

array([ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
        0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
        2.05833592e-312, -7.81747345e-311,  0.00000000e+000,
        0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
        0.00000000e+000,  0.00000000e+000,  2.16443571e-312,
       -8.36918911e-311,  0.00000000e+000,  0.00000000e+000,
        0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
        0.00000000e+000,  2.37663529e-312, -8.71295230e-311,
        0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
        0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
        2.22809558e-312, -9.45565070e-311,  2.46151512e-312,
        2.14321575e-312,  2.20687562e-312,  2.29175545e-312,
        6.79038654e-313,  2.16443571e-312,  2.46151512e-312,
       -1.00158575e-310,  0.00000000e+000,  0.00000000e+000,
        0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
        0.00000000e+000,  8.48798317e-313, -1.04147936e-310,
        0.00000000e+000,

In [101]:
np.empty((30,2))

array([[1.08312127e-311, 1.08311165e-311],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.0

In [111]:
# identity 
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [116]:
# transpose matrix
#wap to create a matrix 3x3.
a = np.array([[1,2,3],[4,5,6],[6,7,8]])

In [117]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [118]:
a.shape

(3, 3)

In [119]:
a.T

array([[1, 4, 6],
       [2, 5, 7],
       [3, 6, 8]])

In [125]:
# linspace
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

In [126]:
# axis = 0 
# axis = 1 
a

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [127]:
a.sum()

42

In [128]:
# axis = 0 ----> col
a.sum(axis = 0)

array([11, 14, 17])

In [129]:
# axis 1 -----> rows
a.sum(axis=1)

array([ 6, 15, 21])