In [1]:
import numpy as np


In [3]:
zero = np.zeros(5)

In [4]:
int(zero)

TypeError: only size-1 arrays can be converted to Python scalars

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
# pandas -----> astype ----->
zero.dtype

dtype('float64')

In [7]:
np.zeros(5,dtype = 'int')

array([0, 0, 0, 0, 0])

In [8]:
#wap to calculate the sum of 3 by 2 matrix wrt col wise & row wise.

arr = np.array([[1,2],[3,4],[5,6]])

In [9]:
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
arr.shape

(3, 2)

In [11]:
arr.sum()

21

In [12]:
# col
arr.sum(axis=0)

array([ 9, 12])

In [13]:
# row
arr.sum(axis = 1)

array([ 3,  7, 11])

In [14]:
#  arg max
# arg min
# sort
# arg sort

arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [30]:
arr = np.array([[[23,78,4],[90,4,21],[78,56,900]]])

In [31]:
arr

array([[[ 23,  78,   4],
        [ 90,   4,  21],
        [ 78,  56, 900]]])

In [19]:
#sort
arr.sort()

In [20]:
arr

array([[[ 4, 23, 78],
        [ 4, 21, 90],
        [43, 56, 78]]])

In [21]:
arr.min()

4

In [22]:
arr.max()

90

In [26]:
#arg -----> sort,min,max

arr

array([[[23, 78,  4],
        [90,  4, 21],
        [78, 56, 43]]])

In [27]:
arr.argsort()

array([[[2, 0, 1],
        [1, 2, 0],
        [2, 1, 0]]], dtype=int64)

In [28]:
arr

array([[[23, 78,  4],
        [90,  4, 21],
        [78, 56, 43]]])

In [32]:
arr.argmax()

8

In [33]:
arr.argmin()

2