In [3]:
import numpy as np

In [4]:
# Create array
arr1 = np.array([1,2,3,4])

In [5]:
arr1

array([1, 2, 3, 4])

In [6]:
type(arr1)

numpy.ndarray

In [8]:
arr1.ndim

1

In [9]:
arr2 = np.array([[23,56,89]])

In [10]:
arr2

array([[23, 56, 89]])

In [11]:
arr2.ndim

2

In [13]:
arr2 = np.array([[23,56,89],[56,78,12]])

In [14]:
arr2

array([[23, 56, 89],
       [56, 78, 12]])

In [15]:
arr2.ndim

2

In [16]:
#shape & size
arr2.shape

(2, 3)

In [17]:
arr2.size

6

In [22]:
arr3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [23]:
arr3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [24]:
arr3.ndim

3

In [27]:
#wap to slice data 5 from arr3.
arr3[0][1][1]

5

In [34]:
arr3[0][0]

array([1, 2, 3])

In [35]:
# max / min
arr3.max()

9

In [37]:
arr3.min()

1