In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])

In [3]:
arr

array([1, 2, 3, 4])

In [5]:
arr.ndim

1

In [6]:
arr.shape

(4,)

In [7]:
arr.size

4

In [8]:
arr = np.array([[1,2,3],[90,56,23]])

In [9]:
arr

array([[ 1,  2,  3],
       [90, 56, 23]])

In [11]:
arr.ndim

2

In [12]:
arr.shape

(2, 3)

In [13]:
arr.size

6

In [14]:
arr = np.array([[[1,2,3]]])

In [15]:
arr

array([[[1, 2, 3]]])

In [16]:
arr.ndim

3

In [17]:
arr.size

3

In [18]:
arr.shape

(1, 1, 3)

In [19]:
arr = np.array([[[1,2,3],[4,5,6],[89,56,0]]])

In [20]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [89, 56,  0]]])

In [21]:
arr.ndim

3

In [22]:
arr.size

9

In [23]:
arr.shape

(1, 3, 3)

In [24]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [89, 56,  0]]])

# Slicing & Indexing

In [31]:
arr[0][1][1]

5

In [32]:
arr.sort()

In [33]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 0, 56, 89]]])

In [34]:
len(arr)

1

In [35]:
arr.max()

89

In [36]:
arr.min()

0

In [40]:
# ones & zeros
np.zeros((6,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [43]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [46]:
# empty/ linspace

np.empty((4,2))

array([[0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 6.24498976e-321],
       [1.11261027e-306, 1.86922094e-306]])

In [52]:
np.linspace(4,6,30)

array([4.        , 4.06896552, 4.13793103, 4.20689655, 4.27586207,
       4.34482759, 4.4137931 , 4.48275862, 4.55172414, 4.62068966,
       4.68965517, 4.75862069, 4.82758621, 4.89655172, 4.96551724,
       5.03448276, 5.10344828, 5.17241379, 5.24137931, 5.31034483,
       5.37931034, 5.44827586, 5.51724138, 5.5862069 , 5.65517241,
       5.72413793, 5.79310345, 5.86206897, 5.93103448, 6.        ])

In [56]:
x = [67,89,45,3]
y = [89,36,12,90]
for i in x:
    for j in y :
        if i == j:
            print("Common",i)
#wap to find common element.

Common 89


In [63]:
#3d data 
# argsort argmax argmin

x = np.array([[[78,90,34],[23,-90,67],[0,5,1]]])

In [64]:
x

array([[[ 78,  90,  34],
        [ 23, -90,  67],
        [  0,   5,   1]]])

In [59]:
x.argmax()

1

In [60]:
x.argmin()

4

In [66]:
x.argsort()

array([[[2, 0, 1],
        [1, 0, 2],
        [0, 2, 1]]], dtype=int64)

In [67]:
x

array([[[ 78,  90,  34],
        [ 23, -90,  67],
        [  0,   5,   1]]])

In [68]:
x

array([[[ 78,  90,  34],
        [ 23, -90,  67],
        [  0,   5,   1]]])

In [69]:
x.sum()

208

In [73]:
x = np.array([[1,2,3],[7,8,9]])

In [74]:
x.sum()

30

In [75]:
x

array([[1, 2, 3],
       [7, 8, 9]])

In [78]:
x.sum(axis = 0)

array([ 8, 10, 12])

In [79]:
x.sum(axis=1)

array([ 6, 24])